
package sk.kopr.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebAjsService", targetNamespace = "http://server.kopr.sk/", wsdlLocation = "http://localhost:8888/ajs?wsdl")
public class WebAjsService
    extends Service
{

    private final static URL WEBAJSSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBAJSSERVICE_EXCEPTION;
    private final static QName WEBAJSSERVICE_QNAME = new QName("http://server.kopr.sk/", "WebAjsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/ajs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBAJSSERVICE_WSDL_LOCATION = url;
        WEBAJSSERVICE_EXCEPTION = e;
    }

    public WebAjsService() {
        super(__getWsdlLocation(), WEBAJSSERVICE_QNAME);
    }

    public WebAjsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBAJSSERVICE_QNAME, features);
    }

    public WebAjsService(URL wsdlLocation) {
        super(wsdlLocation, WEBAJSSERVICE_QNAME);
    }

    public WebAjsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBAJSSERVICE_QNAME, features);
    }

    public WebAjsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebAjsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebAjs
     */
    @WebEndpoint(name = "WebAjsPort")
    public WebAjs getWebAjsPort() {
        return super.getPort(new QName("http://server.kopr.sk/", "WebAjsPort"), WebAjs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebAjs
     */
    @WebEndpoint(name = "WebAjsPort")
    public WebAjs getWebAjsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.kopr.sk/", "WebAjsPort"), WebAjs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBAJSSERVICE_EXCEPTION!= null) {
            throw WEBAJSSERVICE_EXCEPTION;
        }
        return WEBAJSSERVICE_WSDL_LOCATION;
    }

}
