
package sk.kopr.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebAjs", targetNamespace = "http://server.kopr.sk/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebAjs {


    /**
     * 
     * @param priezvisko
     * @param meno
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pridajStudenta", targetNamespace = "http://server.kopr.sk/", className = "sk.kopr.client.PridajStudenta")
    @ResponseWrapper(localName = "pridajStudentaResponse", targetNamespace = "http://server.kopr.sk/", className = "sk.kopr.client.PridajStudentaResponse")
    @Action(input = "http://server.kopr.sk/WebAjs/pridajStudentaRequest", output = "http://server.kopr.sk/WebAjs/pridajStudentaResponse")
    public String pridajStudenta(
        @WebParam(name = "meno", targetNamespace = "")
        String meno,
        @WebParam(name = "priezvisko", targetNamespace = "")
        String priezvisko);

    /**
     * 
     * @param nazov
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pridajCvicenie", targetNamespace = "http://server.kopr.sk/", className = "sk.kopr.client.PridajCvicenie")
    @ResponseWrapper(localName = "pridajCvicenieResponse", targetNamespace = "http://server.kopr.sk/", className = "sk.kopr.client.PridajCvicenieResponse")
    @Action(input = "http://server.kopr.sk/WebAjs/pridajCvicenieRequest", output = "http://server.kopr.sk/WebAjs/pridajCvicenieResponse")
    public String pridajCvicenie(
        @WebParam(name = "nazov", targetNamespace = "")
        String nazov);

    /**
     * 
     * @param datum
     * @param cvicenie
     * @param studenti
     * @return
     *     returns java.lang.String
     * @throws Chyba_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pridajPrezencku", targetNamespace = "http://server.kopr.sk/", className = "sk.kopr.client.PridajPrezencku")
    @ResponseWrapper(localName = "pridajPrezenckuResponse", targetNamespace = "http://server.kopr.sk/", className = "sk.kopr.client.PridajPrezenckuResponse")
    @Action(input = "http://server.kopr.sk/WebAjs/pridajPrezenckuRequest", output = "http://server.kopr.sk/WebAjs/pridajPrezenckuResponse", fault = {
        @FaultAction(className = Chyba_Exception.class, value = "http://server.kopr.sk/WebAjs/pridajPrezencku/Fault/Chyba")
    })
    public String pridajPrezencku(
        @WebParam(name = "cvicenie", targetNamespace = "")
        String cvicenie,
        @WebParam(name = "datum", targetNamespace = "")
        XMLGregorianCalendar datum,
        @WebParam(name = "studenti", targetNamespace = "")
        List<String> studenti)
        throws Chyba_Exception
    ;

    /**
     * 
     * @param uuidc
     */
    @WebMethod
    @RequestWrapper(localName = "zmazCvicenie", targetNamespace = "http://server.kopr.sk/", className = "sk.kopr.client.ZmazCvicenie")
    @ResponseWrapper(localName = "zmazCvicenieResponse", targetNamespace = "http://server.kopr.sk/", className = "sk.kopr.client.ZmazCvicenieResponse")
    @Action(input = "http://server.kopr.sk/WebAjs/zmazCvicenieRequest", output = "http://server.kopr.sk/WebAjs/zmazCvicenieResponse")
    public void zmazCvicenie(
        @WebParam(name = "uuidc", targetNamespace = "")
        String uuidc);

    /**
     * 
     * @param uuids
     */
    @WebMethod
    @RequestWrapper(localName = "zmazStudenta", targetNamespace = "http://server.kopr.sk/", className = "sk.kopr.client.ZmazStudenta")
    @ResponseWrapper(localName = "zmazStudentaResponse", targetNamespace = "http://server.kopr.sk/", className = "sk.kopr.client.ZmazStudentaResponse")
    @Action(input = "http://server.kopr.sk/WebAjs/zmazStudentaRequest", output = "http://server.kopr.sk/WebAjs/zmazStudentaResponse")
    public void zmazStudenta(
        @WebParam(name = "uuids", targetNamespace = "")
        String uuids);

    /**
     * 
     * @param uuidc
     */
    @WebMethod
    @RequestWrapper(localName = "zmazPrezencku", targetNamespace = "http://server.kopr.sk/", className = "sk.kopr.client.ZmazPrezencku")
    @ResponseWrapper(localName = "zmazPrezenckuResponse", targetNamespace = "http://server.kopr.sk/", className = "sk.kopr.client.ZmazPrezenckuResponse")
    @Action(input = "http://server.kopr.sk/WebAjs/zmazPrezenckuRequest", output = "http://server.kopr.sk/WebAjs/zmazPrezenckuResponse")
    public void zmazPrezencku(
        @WebParam(name = "uuidc", targetNamespace = "")
        String uuidc);

    /**
     * 
     * @param uuidc
     * @return
     *     returns java.util.List<sk.kopr.client.Student>
     * @throws Chyba_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "vypisStudentov", targetNamespace = "http://server.kopr.sk/", className = "sk.kopr.client.VypisStudentov")
    @ResponseWrapper(localName = "vypisStudentovResponse", targetNamespace = "http://server.kopr.sk/", className = "sk.kopr.client.VypisStudentovResponse")
    @Action(input = "http://server.kopr.sk/WebAjs/vypisStudentovRequest", output = "http://server.kopr.sk/WebAjs/vypisStudentovResponse", fault = {
        @FaultAction(className = Chyba_Exception.class, value = "http://server.kopr.sk/WebAjs/vypisStudentov/Fault/Chyba")
    })
    public List<Student> vypisStudentov(
        @WebParam(name = "uuidc", targetNamespace = "")
        String uuidc)
        throws Chyba_Exception
    ;

    /**
     * 
     * @param uuids
     * @return
     *     returns java.util.List<sk.kopr.client.Prezencka>
     * @throws Chyba_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "vypisPrezenciek", targetNamespace = "http://server.kopr.sk/", className = "sk.kopr.client.VypisPrezenciek")
    @ResponseWrapper(localName = "vypisPrezenciekResponse", targetNamespace = "http://server.kopr.sk/", className = "sk.kopr.client.VypisPrezenciekResponse")
    @Action(input = "http://server.kopr.sk/WebAjs/vypisPrezenciekRequest", output = "http://server.kopr.sk/WebAjs/vypisPrezenciekResponse", fault = {
        @FaultAction(className = Chyba_Exception.class, value = "http://server.kopr.sk/WebAjs/vypisPrezenciek/Fault/Chyba")
    })
    public List<Prezencka> vypisPrezenciek(
        @WebParam(name = "uuids", targetNamespace = "")
        String uuids)
        throws Chyba_Exception
    ;

}
